# ╔══════════════════════════════════════════════════════════╗
# ║  Kira Linux · fuzzel · 1A "Trinity"                      ║
# ║  frosted launcher : blur comes from Sway layer "launcher"║
# ╚══════════════════════════════════════════════════════════╝

[main]
font=JetBrains Mono:size=13
dpi-aware=no
prompt="  "
icon-theme=Papirus-Dark
icons-enabled=yes
terminal=foot -e
layer=overlay
width=34
lines=8
horizontal-pad=22
vertical-pad=18
inner-pad=12
line-height=26
letter-spacing=0

[colors]

background=09080bb8
text=b09accff
prompt=e8d8ffff
placeholder=6b4f9eff
input=e8d8ffff
match=aa00ffff
selection=aa00ff2b
selection-text=e8d8ffff
selection-match=ff00aaff
border=aa00ff3d
counter=6b4f9eff

[border]
width=1
radius=14

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+g
execute=Return KP_Enter
cursor-left=Left Control+b
cursor-right=Right Control+f
delete-line-backward=Control+u
